### PR TITLE
Locking only in the path that modifies the cache.

### PR DESCRIPTION
**Pull request by jkonecki**
I removed the thread locking that was turing the cache into single-threaded. Locking is done only when the cache is modified.

### CODE REVIEW

**Comment by rsuter** [comment]
Maybe we should implement proper double-checked-locking then...

**Comment by rsuter** [comment]
I.e.: 
```
if (!dictionary.ContainsKey(key))
{
	lock (dictionary)
	{
		if (!dictionary.ContainsKey(key))
		{
			...
		}
	}
}
return dictionary[key];
```
But I'm not sure if `ContainsKey` and `dictionary[key]` is 100% thread-safe...

**Comment by rsuter** [comment]
See http://stackoverflow.com/questions/6018768/double-checked-locking-on-dictionary-containskey

**Comment by rsuter** [comment]
I think there are two options: 

1. Lock whole methods (as is) but with one lock per method (i.e. use dictionary as locks)
2. Use ConcurrentDictionary and double-checked locking (but the current PCL does not support this)

I dont think 1. will degrade performance that much... as soon as a key is loaded its extremely fast (acquiring lock & get existing value)

**Comment by jkonecki** [comment]
I'm confused. I've actually implemented double checked locking in this PR....

**Comment by rsuter** [comment]
The problem is, that in double-checked locking you check outside the lock and inside the lock again and the check (ie. expression in the if) and access must be atomic which `ContainsKey` and `dictionary[key]` aren't... (see the stackoverflow question)

**Comment by jkonecki** [comment]
Ah yes. :-( 

In that case, since we cannot use Concurrent Dictionary, locking on the while method is the way to go. I'll modify PR (will keep 3 separate locks). 
Won't be much of a performance impact since we are single threaded at the moment.

**Pull request merged**
