### PR TITLE
Updating File.txt to add using statements for collections

### PR DESCRIPTION
**Pull request by prateekguru**
Updating File.txt to add using statements for collections (ObservableCollection was missing the required using statement)

### CODE REVIEW

**Comment by rsuter** [comment]
Is this still working with all .NET profiles (i.e. PCL, UWP, etc)?

**Comment by rsuter** [comment]
Otherwise you have to add the namespace manually with the `AdditionalNamespaceUsages` setting.

**Comment by prateekguru** [comment]
I haven't tested it outside of .NET 45.
Also, I cannot find AdditionalNamespaceUsages; Where is that setting?

**Comment by prateekguru** [comment]
I am looking at the Code Generation section primarily.

**Comment by prateekguru** [comment]
Also, the namespaces, I have added to File.txt are available in all versions of .NET that are supported currently. (UWP, Silverlight, .NET 4x and PCL)

**Comment by rsuter** [comment]
Hmm i think this setting is missing here... But you can use the full qualified type name and it should work without additional usages

**Comment by prateekguru** [comment]
Yes, can do that. 
Thanks

**Comment by rsuter** [comment]
But i will think about adding these namespaces..

**Comment by rsuter** [comment]
The namespaces should be available in PCL/all target frameworks... Will be available in the next nuget version.

**Pull request merged**
