### PR TITLE
Added support for validating the IPv6 format

### PR DESCRIPTION
**Pull request by JonAnders**
As defined by section 7.3.5 of JSON Schema draft v4

### CODE REVIEW

**Comment by rsuter** [comment]
Thank you for contributing... Do you need a nuget release?

**Comment by JonAnders** [comment]
Yes, a nuget release would be really helpful :-)

**Comment by rsuter** [comment]
Done: https://www.nuget.org/packages/NJsonSchema/1.32.5904.40563

**Comment by JonAnders** [comment]
Great, thank you!

**Pull request merged**
