### PR TITLE
Added strongnamekey

### PR DESCRIPTION
**Pull request by manojtrek**
Added snk key to the NJSONSchema project, also modified the AssemblyInfo file, updated the InternalToVisible attribute and included the public key.

### CODE REVIEW

**Comment by rsuter** [comment]
Why did you also add signing to the trewhy did you also add signing to the test project?

**Comment by manojtrek** [comment]
No I did not added the signing to the test project.

**Comment by rsuter** [comment]
I cannot sign NJsonSchema.CodeGeneration because Antlr4.StringTemplate is not strong signed. I have to change the template engine anyway because it is not portable (PCL)... The NJsonSchema and NSwag.Core packages are soon available as signed NuGet package

**Comment by rsuter** [comment]
NuGet v2.6 published...

**Pull request merged**
