### PR TITLE
Type to schema fixes

### PR DESCRIPTION
**Pull request by JoshuaWhatley**
Fixed issues:
 - The conversion of types inheriting from Dictionary were failing
 - The generation of non-generic collections (ex: JObject) were failing

### CODE REVIEW

**Comment by rsuter** [comment]
Why would you generate the JSON Schema for JObject? What do you expect?

**Comment by JoshuaWhatley** [comment]
We are using NJsonSchema in conjunction with Swagger (http://swagger.io/) to help present the request / response models of some of our APIs. JObject happens to be present in one of these models.

**Comment by rsuter** [comment]
Just FYI: NJsonSchema is used in http://nswag.org a .NET Swagger toolchain

**Comment by JoshuaWhatley** [comment]
Cool, I wasn't aware of that project. Definitely useful tools, thanks!

**Comment by rsuter** [comment]
Ok, but JObject is a complex object and not serialized as JObject but as its data...

**Comment by JoshuaWhatley** [comment]
I understand. I'll address the JObject scenario before it reaches NJsonSchema. I think it makes more sense that way. I'll remove that test case and the modifications to the array flow.

**Comment by rsuter** [comment]
The other problem can be fixed by uncommenting these lines: 

https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema/JsonObjectTypeDescription.cs#L98
https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema/JsonObjectTypeDescription.cs#L108

The test is here: 
https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema.Tests/Conversion/ArrayTypeToSchemaTests.cs#L11

The problem is that with this enabled, only dictionaries and array types from System.* are directly treated as JSON array, the rest are handled with inheritance... If someone has an own list implementation, the class is generated as own class but not as JSON array...

**Comment by rsuter** [comment]
There is not an easy solution and your change may break other scenarios...

**Comment by rsuter** [comment]
JObject handling is now implemented: 
https://github.com/NJsonSchema/NJsonSchema/blob/master/src/NJsonSchema.Tests/Conversion/TypeToSchemaTests.cs#L187

**Comment by JoshuaWhatley** [comment]
Thanks man, appreciate it.

**Comment by rsuter** [comment]
Ok, both features are now available... see https://github.com/NJsonSchema/NJsonSchema/commit/4572026b2e639ddce7293008b13b1b43111ec8c2

**Pull request closed without merging**
